# Generated by Django 4.0 on 2021-12-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_executor_alter_contract_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='task',
            field=models.TextField(),
        ),
    ]
