# Generated by Django 4.0 on 2021-12-20 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contracts', '0005_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='executor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='contract',
            name='task',
            field=models.TextField(blank=True),
        ),
    ]
